//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleUserLoginForm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultipleUserLoginForm.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _______________.
        /// </summary>
        internal static string ____________________Login_______ {
            get {
                return ResourceManager.GetString("____________________Login_______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _____________.
        /// </summary>
        internal static string ___________________Admin_________________ {
            get {
                return ResourceManager.GetString("___________________Admin_________________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ____________.
        /// </summary>
        internal static string _______________User_Cabinet________ {
            get {
                return ResourceManager.GetString("_______________User_Cabinet________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available objects for the user:.
        /// </summary>
        internal static string runAllAvailableObjects {
            get {
                return ResourceManager.GetString("runAllAvailableObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string runAvailableRightsAccessMatrix {
            get {
                return ResourceManager.GetString("runAvailableRightsAccessMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string runForgotPwd {
            get {
                return ResourceManager.GetString("runForgotPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string runResetPwd {
            get {
                return ResourceManager.GetString("runResetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with the Security Mark:.
        /// </summary>
        internal static string runWithSecurityMark {
            get {
                return ResourceManager.GetString("runWithSecurityMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Matrix.
        /// </summary>
        internal static string textBlockAccessMatrix {
            get {
                return ResourceManager.GetString("textBlockAccessMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string textBlockExitAdmin {
            get {
                return ResourceManager.GetString("textBlockExitAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string textBlockInformation {
            get {
                return ResourceManager.GetString("textBlockInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string textBlockLog {
            get {
                return ResourceManager.GetString("textBlockLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string textBlockPath {
            get {
                return ResourceManager.GetString("textBlockPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Mark:.
        /// </summary>
        internal static string textBlockSecurityMark {
            get {
                return ResourceManager.GetString("textBlockSecurityMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set of Objects.
        /// </summary>
        internal static string textBlockSetOfObjects {
            get {
                return ResourceManager.GetString("textBlockSetOfObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set of Subjects.
        /// </summary>
        internal static string textBlockSetOfSubjects {
            get {
                return ResourceManager.GetString("textBlockSetOfSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string textBlockSettings {
            get {
                return ResourceManager.GetString("textBlockSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string textBlockUserLogin {
            get {
                return ResourceManager.GetString("textBlockUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username.
        /// </summary>
        internal static string txtUserNameUserLoginHint {
            get {
                return ResourceManager.GetString("txtUserNameUserLoginHint", resourceCulture);
            }
        }
    }
}
